### PR TITLE
V8 performance optimizations

### PR DESCRIPTION
**Pull request by pakastin**
1) arguments should not be leaked / sliced:
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

2) added todo (because don't know how to fix): try/catch should be removed!
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#2-unsupported-syntax

### CODE REVIEW

**Comment by pakastin** [comment]
I believe those issues makes the most time waste:
profiling

**Comment by GianlucaGuarini** [comment]
Cool this looks really useful Thank you
I would prefer a single helper function to handle the conversion:

``` js
function getArgsAsArray(args) {
   var length = args.length,
      arr = new Array(length)
    for (var i = 0; i < length; i++) {
      arr[i] = args[i]
    }
    return arr
 }
```

> added todo (because don't know how to fix): try/catch should be removed!

How would you solve then https://github.com/riot/observable/issues/3 ?

**Comment by pakastin** [comment]
It must be in-line:

> The arguments object must not be passed or leaked anywhere.
> Workaround for proxying is to create array in-line

**Comment by GianlucaGuarini** [comment]
Ah ok I see, it's not nice but it's worth to try

**Comment by pakastin** [comment]
I know, I dislike it as well, but what can you do.. `arguments` seems to be a special kind of array in these situations.. But that try/catch needs to be fixed as well, @tipiirai had some idea for that..?

**Comment by pakastin** [comment]
Oh, that must've been [different place](https://github.com/riot/riot/issues/990#issuecomment-145466344).

**Pull request merged**
