### PR TITLE
Feature/remove spaced events

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
This patch makes riot-observable ~22% faster and a lot simpler but it removes the spaced events support
I think it's totally worth if we want make riot@3.0.0 faster
Patched observable

```
new-observable#simple event x 2,847,010 ops/sec ±1.12% (91 runs sampled)
new-observable#namespaced event x 2,891,754 ops/sec ±1.09% (91 runs sampled)
```

Current observable

```
new-observable#simple event x 2,233,131 ops/sec ±1.65% (90 runs sampled)
new-observable#namespaced event x 2,336,702 ops/sec ±0.87% (93 runs sampled)
```

Please let me know what you think
@tipiirai @rsbondi @aMarCruz @cognitom @rogueg

### CODE REVIEW

**Comment by rvion** [comment]
I personally don't need them, I have no problem having them removed, and will be quite happy to see riot being faster

**Comment by 5angel** [comment]
I agree, even when I can use spaced events, I usually want to pass separate sets of data, so I divide them anyway.

**Comment by juodumas** [comment]
I fully agree about removing this edge case -> making events simpler, but only because I haven't got anything using riot2.

But one more thing: does riot really need to support namespaced events, which you have recently pulled in for riot2 and riot3? Looks like exchanging one edge case over aother..

**Comment by GianlucaGuarini** [comment]
I guess the namespaced events must be removed because they are causing problems in our riot router https://github.com/riot/route/issues/63 I will update this pull request

**Comment by GianlucaGuarini** [comment]
Bench without namespaced events:

```
new-observable#simple event x 3,973,287 ops/sec ±2.02% (79 runs sampled)
```

I am going to merge this looking forward to testing it in riot@3.0.0

**Comment by juodumas** [comment]
Looks like riot-3 is all about cutting corner cases. I like that.

**Comment by Mouvedia** [comment]
@GianlucaGuarini Concretely this means that for `on`

```
element.on('start stop', function(type) {});
```

will have to be written

```
element.on('start', function() {});
element.on('stop', function() {});
```

from now on?

Doesn't that warrant something like

```
element
   .stop(function() {})
   .start(function() {});
```

?

That would be much more elegant.

**Comment by GianlucaGuarini** [comment]
@Mouvedia your api proposal does not really make sense here since you could already do it http://plnkr.co/edit/fpRNmDWxv7BorDprebdI?p=preview  even if I would not recommend it

**Comment by senica** [comment]
I was sad to see namespaced events go away. I rely heavily on global events happening to keep the individual components updated. Namespaces make it easy to do `app.on('somethingHappened.'+_riot_id)` and then in the 'before-unmount' event, turn it off: `app.off('somethingHappened.'+_riot_id)`. Not having namespaces, makes this extremely difficult.

**Comment by juodumas** [comment]
@senica: just create a mixin which calls `.on` immediately and calls `.off` in `before-unmount`.

I use `this.onoff(app, 'eventName', () => { do_something })`.

**Comment by GianlucaGuarini** [comment]
@senica relying on `_riot_id` to handle your app logic it's a symptom of code smell. `_riot_id` is a "private" internal property, it could change at any time and it does not belong to the riot api. For all those that want to still using the slow namespaced events shooting on their feets you can use this simple mixin http://plnkr.co/edit/N0AIQKyp5ZyagemgwZfi?p=preview

**Comment by senica** [comment]
@GianlucaGuarini Thanks for pointing out that _riot_id is internal. I realize this is not the place for this, but I would argue that an ID should be just that,  an identifier — regardless if meant to be internal or not. Saying that it "could" change at anytime and be disassociated with the tag does not classify it to be an identifier.

I must have confused myself at some point with how the observable api worked, because I had an issue where a self looping tag would not unbind the event, and my call stack just kept increasing. Perhaps, the issue was elsewhere and I didn't realize. In any case, after going back and testing and everything was working, nice work in removing the namespaces ;)

**Pull request merged**
